# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '\u7b54\u6848', 'verbose_name_plural': '\u7b54\u6848'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '\u95ee\u9898', 'verbose_name_plural': '\u95ee\u9898'},
        ),
    ]
